import os
from groq import Groq
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

SYSTEM_PROMPT = """
You are Antigravity, an AI-powered Minutes of Meeting (MoM) generator.

System Architecture:
- Whisper (open-source) is used to convert meeting audio into text.
- Groq Cloud (Llama 3 / Mixtral) is used to analyze the transcript.

Your role:
You receive a raw meeting transcript generated by Whisper.
The transcript may contain filler words, interruptions, informal language,
and transcription noise.

Your task is to clean, understand, and summarize the transcript into
professional Minutes of Meeting suitable for official documentation.

Generate the output in the following Markdown format:

| Field | Detail |
| :--- | :--- |
| **1. Meeting Title** | (Infer from context) |
| **2. Date & Time** | (If available; otherwise "Not mentioned") |
| **3. Attendees** | (Only if clearly mentioned) |

---

### 4. Meeting Summary
(Concise and professional narrative summary of the meeting)

### 5. Key Discussion Points
*   (Point 1)
*   (Point 2)
*   (Point 3)

### 6. Decisions Made
*   (Decision 1)
*   (Decision 2)

### 7. Action Items

| Task | Owner | Deadline |
| :--- | :--- | :--- |
| (Task Description) | (Owner Name) | (Deadline) |

### 8. Next Steps / Follow-ups
(Brief paragraph or bullet points on clear next steps)

Guidelines:
- Do NOT hallucinate facts, names, or decisions.
- If information is missing, clearly state "Not mentioned".
- Remove filler words and irrelevant conversation.
- Maintain a formal and professional tone.
- Keep the output well-structured using the exact headers and tables provided above.
"""

class MinutesGenerator:
    def __init__(self, api_key=None, model="llama-3.3-70b-versatile"):
        """
        Initialize the MinutesGenerator with Groq.
        Args:
            api_key (str): Groq API key.
            model (str): Groq model name (default: "llama-3.3-70b-versatile").
        """
        # Prioritize key in .env
        actual_key = api_key or os.getenv("GROQ_API_KEY")
        
        if not actual_key:
             raise ValueError("Groq API Key is missing. Please set it in .env file as GROQ_API_KEY.")
             
        self.client = Groq(api_key=actual_key)
        self.model_name = model

    def generate_minutes(self, transcript):
        """
        Generate meeting minutes from the provided transcript using Groq.
        Args:
            transcript (str): The raw meeting transcript.
        Returns:
            str: The generated meeting minutes.
        """
        print(f"Generating meeting minutes with Groq ({self.model_name})...")
        try:
            response = self.client.chat.completions.create(
                model=self.model_name,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": f"Transcript:\n{transcript}"}
                ],
                temperature=0.7
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"Error generating minutes: {str(e)}"
